Add support for 3D meshes in ScaleByAreaAction
precice/precice pull request #1072
Opened 2021-08-31 22:22 UTC by mhmdkanj

## Main changes of this PR

Extend the ScaleByAreaAction to apply to 3D meshes as well instead of 2D meshes only.

## Motivation and additional information

closes #752 

## Author's checklist

* [x] I added a changelog file with this PR number in `docs/changelog/` if there are noteworthy changes -> **Not so worthy to add to Changelog**
* [x] I ran `tools/formatting/check-format` and everything is formatted correctly.
* [x] I sticked to C++14 features.
* [x] I sticked to CMake version 3.10.
* [x] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?
* [ ] (more questions/tasks)

2021-09-02 12:31 UTC, uekerman requested changes
Looks good. Thanks for the contribution.

These checks also need to be removed to make it work.

https://github.com/precice/precice/blob/c186fd0ec8e57337c0ecaebb78efd55ea266fef3/src/action/config/ActionConfiguration.cpp#L244-L256

And I think it's worth a changelog entry.
"Added support for ..."

2021-09-03 16:20 UTC, mhmdkanj commented
@uekerman Thanks for your feedback!
I've already integrated those suggestions now.

2021-09-07 14:11 UTC, uekerman approved these changes

2021-09-07 15:37 UTC, DavidSCN commented
Do we catch (via error messages) the case where someone tries to use the feature without defining connectivity in 3D?

2021-09-09 00:38 UTC, mhmdkanj commented
> Do we catch (via error messages) the case where someone tries to use the feature without defining connectivity in 3D?

@DavidSCN Currently, calling this function/action assumes already that some connectivity is defined (creation of edges in 2D OR creation of triangles in 3D). So if such connectivity is NOT defined, then no error messages are thrown during the process.

Throwing an exception or doing checks in the action config in this case would be beneficial in the sense that calling the scaling action would prevent the nullification (in case of multiplication) or division by zero (in case of division) of the target values. Would that be a possible scenario when using this action while not defining connected vertices in 2D nor 3D?

2021-09-09 06:05 UTC, DavidSCN commented
> > Do we catch (via error messages) the case where someone tries to use the feature without defining connectivity in 3D?
> 
> @DavidSCN Currently, calling this function/action assumes already that some connectivity is defined (creation of edges in 2D OR creation of triangles in 3D). So if such connectivity is NOT defined, then no error messages are thrown during the process.
> 
> Throwing an exception or doing checks in the action config in this case would be beneficial in the sense that calling the scaling action would prevent the nullification (in case of multiplication) or division by zero (in case of division) of the target values. Would that be a possible scenario when using this action while not defining connected vertices in 2D nor 3D?

Yes, I assume that this might be a frequent issue since not even all of our official adapter support setting connectivity. If you want to implement this you could use something like `PRECICE_CHECK( cond, message)`, where the condition checks for the existence of the connectivity. If you don't want to implement this, please open up an issue so that we keep it in mind.

2021-09-10 12:45 UTC, uekerman commented
> Throwing an exception or doing checks in the action config

In the configuation of the action, we cannot already check for this since at this point meshes are not filled yet. Such a check would need to go into `ScaleByAreaAction::performAction`.

@mhmdkanj We can also fix this in a separate PR. If it's easy for you, you can do it here. If you are puzzled what to do, let's merge here and open a separate issue and/or PR.

2021-09-10 12:53 UTC, mhmdkanj commented
> In the configuation of the action, we cannot already check for this since at this point meshes are not filled yet. Such a check would need to go into `ScaleByAreaAction::performAction`.
> 
> @mhmdkanj We can also fix this in a separate PR. If it's easy for you, you can do it here. If you are puzzled what to do, let's merge here and open a separate issue and/or PR.

@uekerman Yup, I just realized that when executing the tests. Please check the second commit if these checks are appropriate. Thanks in advance!

2021-09-12 09:40 UTC, uekerman approved these changes
Minor tweaks to the text. Otherwise looks good :+1:

2021-09-12 09:40 UTC, uekerman commented on src/action/ScaleByAreaAction.cpp
> +                  "The scaling action expects a connected 2D mesh. Please ensure that the mesh contains at least one \"edge\".");
```suggestion
                  "The multiply/divide-by-area actions require meshes with connectivity information. In 2D, please ensure that the mesh {} contains edges.",  getMesh()->getName());
```

2021-09-12 09:40 UTC, uekerman commented on src/action/ScaleByAreaAction.cpp
> +                  "The scaling action expects a connected 3D mesh. Please ensure that the mesh contains at least one \"triangle\".");
```suggestion
                   "The multiply/divide-by-area actions require meshes with connectivity information. In 3D, please ensure that the mesh {} contains triangles.",  getMesh()->getName());
```

2021-09-13 06:09 UTC, DavidSCN approved these changes

2021-09-13 06:09 UTC, merged

2021-09-13 06:46 UTC, uekerman commented
@mhmdkanj Thanks for the contribution again and congrats on the first merge :tada: :grinning: 

Small technical remark: force pushes are sometimes good, but not always necessary. For such PRs, we often anyway squash & merge, so it's no problem if there are many commits. And for reviewing it's sometimes easier to also see the delta in between review cycles. Otherwise, great work.