Restructure integration tests
precice/precice pull request #1205
Opened 2022-03-16 14:51 UTC by DavidSCN

## Main changes of this PR

Restructure the serial and parallel integration tests as discussed in #1149.

## Motivation and additional information

Depends on #1202 

## Author's checklist

* [ ] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [ ] I ran `make format` to ensure everything is formatted correctly.
* [x] I sticked to C++14 features.
* [x] I sticked to CMake version 3.10.
* [ ] I squashed / am about to squash all commits that should be seen as one.
* [ ] Open issue on unmaintained tests (e.g. the parallel [multi-coupling tests](https://github.com/precice/precice/blob/ebce55ab5c563295909b0179f6610b6e4d4fa529/src/precice/tests/ParallelTests.cpp#L1655-L1674)

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

2022-03-25 12:38 UTC, BenjaminRodenberg requested changes
Already looks very good.

Open points I see here:

* In `ParallelTests.cpp` and `SerialTests.cpp` there is still dead code. @fsimonis can you comment here? We should either revive the tests, open an issue or delete them (we can still revive them later from the history). https://github.com/precice/precice/commit/503ecca4a6c8a17b299f735e8e211e13ad29b9d4 and https://github.com/precice/precice/commit/bd0e158aa0cc795ba0c7b227cf1c086c73cbc896 are the relevant commits here from my perspective.
* Are the remaining configuration files in `precice/tests` actually needed? If not, we should also delete them. `explicit-direct-access-two-level.xml` seems to be unused; `cplmode-1.xml` is also unused; `explicit-mpi-single-non-inc.xml` is only used by a commented out test. `config-checker.xml` is fine, because it is used by `ToolingTests.cpp`.

2022-03-25 12:56 UTC, DavidSCN commented
The ParallelTests are actually already a TODO in the checklist on top. The dead SerialTests are somewhat of a crime by @fsimonis and I don't know what to do with them. I will clean-up the xml files.

2022-03-25 12:58 UTC, fsimonis commented
@DavidSCN don't shoot the one that formatted the entire codebase. :grin:

2022-03-25 14:00 UTC, fsimonis commented
@DavidSCN you can remove the resetMesh serial tests, I will implement a complete test suite instead. This closes #1100

@uekerman @oguzziya Do you remember why the parallel tests regarding multi-coupling-schemes were disable in https://github.com/precice/precice/pull/1025/commits/8354dab48c10000f787eea48762a80c1bcb80ca4?

2022-03-26 11:21 UTC, DavidSCN commented
@fsimonis No shots fired ;)

> Do you remember why the parallel tests regarding multi-coupling-schemes were disable in https://github.com/precice/precice/commit/8354dab48c10000f787eea48762a80c1bcb80ca4?

Answer from @oguzziya was 

> they are to be added once [precice/precice#1025](https://github.com/precice/precice/pull/1025) also works for a parallel "controller"/ the cases were supposed to be failing right now

I will open up an issue on that.

2022-03-26 14:06 UTC, BenjaminRodenberg approved these changes
Looks good :+1: Minor comments below, but from my perspective this is good to go.

2022-03-26 14:08 UTC, DavidSCN commented on src/tests.cmake
>      src/precice/tests/ParallelTests.cpp
I have actually no choice because this no handled by `make sourceIndex` (also removing them) and as long as the file exists it will be added here.

2022-03-26 14:10 UTC, BenjaminRodenberg commented on src/tests.cmake
>      src/precice/tests/ParallelTests.cpp
Ok. Not important anyway.

2022-03-28 19:09 UTC, merged