Iqn updates main
precice/precice pull request #1493
Opened 2022-11-29 12:17 UTC by KyleDavisSA

## Main changes of this PR
This PR closes #1152 due to being too old. The reason for this PR are copied from #1152.

1. Automatically deletes the first column in time step 4 if an initial sub-vector from at least 1 solver is zero, measured by the L2 norm.
2. Monitors the residual sum preconditioner weights and only updates them if they change by a specified factor. This is required for faster QR filtering.

## Motivation and additional information

Currently the preconditioner weights are updated in every iteration. This is unnecessary if the weights change by a small value, but the entire QR decomposition is performed again. Vast improvements in runtime can be found by not always updating the preconditioner weights.

## Author's checklist

* [ ] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* [ ] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [ ] I added a test to cover the proposed changes in our test suite.
* [ ] I sticked to C++17 features.
* [ ] I sticked to CMake version 3.16.3.
* [ ] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

* [ ] Allow preconditioner weight monitoring to be turned on/off via the config file.
* [ ] Allow column deletion to be turned on/off via the config file.
* [ ] Include the fast QR filter when preconditioner weight monitoring is applied.
* [ ] Include tests for QR filters
* [ ] Update user documentation

2025-02-24 09:21 UTC, uekerman requested changes
Thanks for taking care of this one, highly appreciated :pray: 

- Do we actually need the "updatePreconLimit" as a configuration option? Would we ever want to use a different value than 10?
- Should we update the default ILS and IMVJ configurations? (If yes, please also update the changelog) I would not consider this breaking.
- Could we unit-test the QR3 filter somehow? Currently, we don't test anywhere that it actually does the right thing, correct?

2025-02-24 09:21 UTC, uekerman commented on src/acceleration/impl/Preconditioner.hpp
> +  }
areUpdated or wereUpdated?

2025-02-24 09:21 UTC, uekerman commented on src/acceleration/impl/QRFactorization.cpp
> +      PRECICE_DEBUG("  Pre-scaling weights were reset. Reverting to QR2 and rebuilding QR.");
```suggestion
      PRECICE_DEBUG("Pre-scaling weights were reset. Reverting to QR2 and rebuilding QR.");
```

2025-02-24 09:21 UTC, uekerman commented on src/acceleration/impl/ResidualSumPreconditioner.cpp
> +    // Check if the new scaling weights are more or less than 1 order of magnitude from the previous weights
The "1" here is now configurable (`updatePreconLimit`), right? Also in the Debug statement below.

2025-02-24 09:21 UTC, uekerman commented on src/acceleration/impl/ResidualSumPreconditioner.cpp
> +        std::cout << "_previousResidualSum[k]: " << _previousResidualSum[k] << std::endl;
No `std::cout` please.

2025-02-24 09:21 UTC, uekerman commented on src/acceleration/impl/ResidualSumPreconditioner.hpp
> +  ResidualSumPreconditioner(int maxNonConstTimeWindows, bool = true, double updatePreconLimit = 10.0);
```suggestion
  ResidualSumPreconditioner(int maxNonConstTimeWindows, bool preconForceUpdate = true, double updatePreconLimit = 10.0);
```
??
Why do you need the defaults here? Aren't these covered in the configuration already?

2025-02-24 09:21 UTC, uekerman commented on tests/quasi-newton/serial/TestQN15.cpp
> +  // serial coupling, IQN-IMVJ acceleration, to test `RS-SVD` method for restart;
This comment probably needs an update?

2025-02-24 09:21 UTC, uekerman commented on src/acceleration/config/AccelerationConfiguration.cpp
> +      VALUE_RESIDUAL_SUM_LIMIT("limit"),
If we keep this limit configurable, we need to make both names consistent.
Either "on-limit" and "limit". Or "on-threshold" and "threshold".

2025-02-24 09:21 UTC, uekerman commented on src/acceleration/config/AccelerationConfiguration.cpp
> +                                                          "If this tag is not provided, the preconditioner weights are updated after every iteration when it's not frozen.");
How does "always" and "frozen" interplay?
Shouldn't we make "frozen" an option here as well?
(similarly for IMVJ below)

2025-02-25 17:04 UTC, Fujikawas commented on src/acceleration/config/AccelerationConfiguration.cpp
> +                                                          "If this tag is not provided, the preconditioner weights are updated after every iteration when it's not frozen.");
As I understand from the paper: 
There is an option to define the time window number to start freezing the scaling weights. 
If this number is larger than 1,  we check the option `always` or `on-threshold`. If it's `always`, the weights will be recomputed after every iteration, otherwise from the 2nd time window, the weights will be updated when it's dramatically changing.
If the number is one, then `always` and  `on-threshold` are the same.

I think to change it into a boolean named "update_on_threshold"  may make this option easier to understand.

2025-03-03 15:29 UTC, uekerman commented
> After setting the default filter to QR3, now it's used in several integration tests.

True, but those integration tests typically only test that it doesn't break, not that the filter does the correct thing, no?

2025-03-03 15:39 UTC, uekerman commented on docs/changelog/1493.md
> +- Added QR3 filter and weight monitoring for residual-sum preconditioner. Set QR3 as default filter.
```suggestion
- Added QR3 filter and use it in default IQN-ILS and IQN-IMVJ configurations (see https://doi.org/10.3390/mca27030040).
- Added weight monitoring for residual-sum preconditioner and use it in default IQN-ILS and IQN-IMVJ configurations (see https://doi.org/10.3390/mca27030040).
```

2025-03-03 15:39 UTC, uekerman commented on src/acceleration/config/AccelerationConfiguration.cpp
> +                                                                     "When this tag is not provided, the value is set to `true` by default.");
No need to document the default. This is automatically rendered, see https://precice.org/configuration-xml-reference.html

2025-03-03 15:39 UTC, uekerman commented on src/acceleration/config/AccelerationConfiguration.cpp
> +                                                                     "When this tag is not provided, the value is set to `true` by default.");
see above

2025-03-03 15:39 UTC, uekerman commented on src/acceleration/config/AccelerationConfiguration.cpp
> +                                                                     "- `true`: The preconditioner weights are only updated if the relative difference of the weights is larger than the limit.\n"
now you removed the "limit", right? Then, we should also update the docs here

2025-03-03 15:39 UTC, uekerman commented on src/acceleration/config/AccelerationConfiguration.cpp
> +                                                                     "- `true`: The preconditioner weights are only updated if the relative difference of the weights is larger than the limit.\n"
see above

2025-03-24 08:33 UTC, uekerman approved these changes

2025-03-24 08:34 UTC, merged

2025-03-24 13:42 UTC, MakisH commented
@uekerman the system tests run you triggered failed immediately, as branches from forks are not yet supported. I triggered a new one on the merged commit: https://github.com/precice/tutorials/actions/runs/14036757914/job/39296515606

This is now failing with results regressions, so the regression was introduced in with this PR, and not in the substeps one. (cc @BenjaminRodenberg)