Optional stacktrace generation with libbacktrace
precice/precice pull request #1538
Opened 2023-01-16 10:10 UTC by fsimonis

## Main changes of this PR

Add optional (disabled by default) support for stacktraces with libbacktrace.

To use, enable the CMake option `PRECICE_ENABLE_LIBBACKTRACE`.
This will extract and install libbacktrace from the thirdparty folder and setup boost.stacktrace.
The library will be statically linked against preCICE.

## Motivation and additional information

Since #1498, the default method of stacktrace generation doesn't generate usable stacktraces as the default implementation ignores debug symbols. 

Motivation for adding the library to the thirdparty folder is that this is a developer only tool, which is disabled by default. No distro packages libbacktrace and it has not versioning apart from the commit history.

Closes #1519

## Author's checklist

* [ ] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* [ ] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [ ] I added a test to cover the proposed changes in our test suite.
* [ ] For breaking changes: I documented the changes in the appropriate [porting guide](https://precice.org/couple-your-code-porting-overview.html).
* [ ] I sticked to C++17 features.
* [ ] I sticked to CMake version 3.16.3.
* [ ] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

2023-01-16 10:11 UTC, fsimonis commented
Would `PRECICE_ENABLE_LIBBACKTRACE` be a better name compared to the current `PRECICE_ENABLE_BACKTRACE`?

2023-01-16 11:02 UTC, BenjaminRodenberg commented
> Would `PRECICE_ENABLE_LIBBACKTRACE` be a better name compared to the current `PRECICE_ENABLE_BACKTRACE`?

Spontaneous thought: Backtrace is what we do. Libbacktrace is just the current implementation. Imagine we switch to a different implementation (using for example `libawesometraces`, which I just made up) we would need to change the name of the option.

2023-01-16 11:33 UTC, fsimonis commented
An alternative to using non-existent packages could be to download and compile libbacktrace as an externalproject in the build directory. This way the developer doesn't to handle the entire setup of the pkg-config file etc.

2023-01-16 15:34 UTC, fsimonis commented
Just talked to @uekerman. We will try to integrate libbacktrace directly as a third party library

2023-01-17 16:06 UTC, fsimonis commented
I added libbacktrace to the thirdparty repo and updated the option name.

2023-01-19 10:05 UTC, BenjaminRodenberg requested changes
I merged this PR into #1523 and got the following errors when trying to build:

```
precice/build$ cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPRECICE_PythonActions=off -DPRECICE_ENABLE_LIBBACKTRACE=ON ..

precice/build$ make -j8
...
-- === ENABLED FEATURES ===
...
 * libbacktrace, Enables libbacktrace for stracktrace generation.

   preCICE assertions are helpful during development, however, the default stacktraces may not be sufficent.
   This feature enables the support for libbacktrace in boost.stacktrace.

   This feature can be enabled/disabled by setting the PRECICE_ENABLE_LIBBACKTRACE CMake option.
...
[ 34%] Building CXX object CMakeFiles/preciceCore.dir/extras/bindings/fortran/src/SolverInterfaceFortran.cpp.o
[ 34%] Built target preciceCore
Scanning dependencies of target precice
Scanning dependencies of target testprecice
make[2]: *** No rule to make target 'thirdparty/libbacktrace/libbacktrace.a', needed by 'libprecice.so.2.5.0'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:278: CMakeFiles/precice.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 35%] Building CXX object CMakeFiles/testprecice.dir/src/testing/main.cpp.o
...
[ 99%] Building CXX object CMakeFiles/testprecice.dir/tests/serial/whitebox/TestConfigurationComsol.cpp.o
make[2]: *** No rule to make target 'thirdparty/libbacktrace/libbacktrace.a', needed by 'testprecice'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 99%] Building CXX object CMakeFiles/testprecice.dir/tests/serial/whitebox/TestConfigurationPeano.cpp.o
make[1]: *** [CMakeFiles/Makefile2:386: CMakeFiles/testprecice.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

After configuring with `-DPRECICE_ENABLE_LIBBACKTRACE=OFF`, building works (but, I guess no stacktrace).

2023-01-19 18:24 UTC, fsimonis commented
libbacktrace should be build when running cmake.
You should the find the header and the archive in the build directory in thirdparty/libbacktrace.

Can you check this happens?

2023-01-20 10:21 UTC, BenjaminRodenberg commented
> libbacktrace should be build when running cmake. You should the find the header and the archive in the build directory in thirdparty/libbacktrace.
> 
> Can you check this happened? You may need to configure from scratch.

Looks quite empty, but I realized that there also were a few errors:

```
precice$ rm -r build/
precice$ mkdir build
precice$ cd build/
precice/build$ cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPRECICE_PythonActions=off -DPRECICE_ENABLE_LIBBACKTRACE=ON ..
...
-- Preparing libbacktrace
-- Extracting sources
CMake Error at thirdparty/libbacktrace/CMakeLists.txt:9 (file):
  file does not recognize sub-command ARCHIVE_EXTRACT


-- Running autoconf
CMake Error at thirdparty/libbacktrace/CMakeLists.txt:18 (execute_process):
  execute_process given unknown argument "COMMAND_ERROR_IS_FATAL".


-- Running ./configure
CMake Error at thirdparty/libbacktrace/CMakeLists.txt:18 (execute_process):
  execute_process given unknown argument "COMMAND_ERROR_IS_FATAL".


-- Running make
CMake Error at thirdparty/libbacktrace/CMakeLists.txt:18 (execute_process):
  execute_process given unknown argument "COMMAND_ERROR_IS_FATAL".


-- Copying files
CMake Error at thirdparty/libbacktrace/CMakeLists.txt:26 (file):
  file COPY cannot find
  "/home/benjamin/Programming/precice/build/thirdparty/libbacktrace/libbacktrace-master/backtrace.h":
  No such file or directory.


-- libbacktrace built successfully
...
-- Configuring incomplete, errors occurred!
precice/build$ ls thirdparty/
fmt/          json/         libbacktrace/ 
precice/build$ ls thirdparty/libbacktrace/
CMakeFiles
precice/build$ ls thirdparty/libbacktrace/CMakeFiles/

```

2023-01-20 10:25 UTC, BenjaminRodenberg commented on CMakeLists.txt
> +# Option ENABLE_BACKTRACE
```suggestion
# Option ENABLE_LIBBACKTRACE
```

2023-01-20 10:53 UTC, fsimonis commented
Aha we are still stuck with cmake 3.16.3....

I'll come up with a backport and enable this in the CI

2023-01-20 12:48 UTC, fsimonis commented on CMakeLists.txt
> +option(PRECICE_ENABLE_LIBBACKTRACE "Enable libbacktrace for stacktrace generation." OFF)
Sadly no and this is also quite confusing. There is backtrace (which is found by CMakes FindBacktrace) and there is libbacktrace. Both have different interfaces.
Boost stacktrace uses the libbacktrace interface.

2023-01-20 12:52 UTC, fsimonis commented
I backported the CMake to 3.16 and enabled libbacktrace in the linux CI.

2023-01-20 12:56 UTC, BenjaminRodenberg approved these changes
Now everything works nicely :+1: 

Last open point: We should also make sure that this works by enabling it in the CI. Output is useful in the logs and we also get a warning early if this feature (which is probably not used by everybody) breaks.

2023-01-20 12:57 UTC, BenjaminRodenberg commented on CMakeLists.txt
> +option(PRECICE_ENABLE_LIBBACKTRACE "Enable libbacktrace for stacktrace generation." OFF)
Ok. I think I understand the reason.

2023-01-27 14:50 UTC, BenjaminRodenberg commented
@fsimonis Currently there is an error in the CI pipeline: https://github.com/precice/precice/actions/runs/3969218777/jobs/6803414018#step:11:177

As far as I remember, I did not observe these kind of problems. If I can help here, please let me know. Would be great, if we could merge this PR soon, because the stacktrace is superuseful.

2023-01-30 12:28 UTC, fsimonis commented
The symlink chain of libbacktrace is incorrect, hence the missing `so.0`.
It should be a chain `libbacktrace.so -> .so.0 -> .so.0.0 -> libbacktrace.so.0.0.0`, but they all link directly to `.so.0.0.0`.

2023-02-23 10:47 UTC, BenjaminRodenberg commented
@fsimonis Is this PR ready to merge?

2023-02-23 11:08 UTC, merged