Add missing xml error handlers
precice/precice pull request #1574
Opened 2023-02-20 15:54 UTC by fsimonis

## Main changes of this PR

This PR adds missing error handlers for libxml2.

## Motivation and additional information

Tag mismatches are correctly handled now.

```
ERROR: Opening and ending tag mismatch: configuration line 2 and figuration
```

Closes #1564

## Author's checklist

* [x] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* [ ] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [ ] I added a test to cover the proposed changes in our test suite.
* [ ] For breaking changes: I documented the changes in the appropriate [porting guide](https://precice.org/couple-your-code-porting-overview.html).
* [x] I sticked to C++17 features.
* [x] I sticked to CMake version 3.16.3.
* [x] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

2023-02-21 11:35 UTC, davidscn requested changes
I built preCICE in release and added the following lines to my config

```xml
      <mapping:rbf
        direction="read"
        from="Solid-Mesh"
        to="Fluid-Mesh"
        constraint="consistent" >
         <basis-function:compact-polynomial-c0 support-radius="1" />
      </mapping:rbf-global-iterative>
```

which still triggers the silent crash, i.e., the mismatch is not detected properly.

This might be related to the mapping, though, es we have a `nullptr` in the mapping object for the RBF mapping. The mapping is only instantiated in the subtag, see
https://github.com/precice/precice/blob/fcefb9d6620f8d4f8dfefa574bbcd44002ce7adf/src/mapping/config/MappingConfiguration.cpp#L453-L455

2023-02-21 15:03 UTC, fsimonis commented
@davidscn I get the following error for your config in both Debug and Release builds:

```
ERROR: Opening and ending tag mismatch: rbf line 28 and rbf-global-iterative
```

2023-02-21 16:16 UTC, davidscn commented
I only get the error message you mention when using `precice-tools`.
Running _the same_ config with a real solver still leads to the silent crash (tested with OpenFOAM and deal.II). Even the debug build fails immediately, it seems that preCICE dies on the spot. Have you tried with a real solver?

2023-02-22 12:15 UTC, fsimonis commented
This took me some while to reproduce, but I am finally managed it.


perpendicular-flap with {fluid-nutils, solid-dealii} doesn't output any error in case of mismatching tags, but it silently crashes.

Using the `log.conf` to configure an output stream works and the error is nicely displayed.
```
[HelpMe]
Filter = 
Type = stream
output = stdout
```

Hence, we are running into an old problem: 
During the parsing stage of the configuration, preCICE doesn't have a logger setup.
Hence, error messages are not displayed.

Tests and `precice-tools check` create a logger beforehand, hence it doesn't affect them.
Hence, this is only visible the using solvers that link to the library.
So, this can easily be reproduced using the solverdummies.

The behaviour was most likely introduced with #1305

2023-02-22 12:40 UTC, fsimonis commented
Fixed the bug here. I am not adding a changelog entry ass this was introduced after the last release.

2023-02-22 12:44 UTC, davidscn approved these changes
Works now, nice!

2023-02-22 12:48 UTC, merged