add default settings to IQN-ILS and IQN-IMVJ acceleration methods
precice/precice pull request #1754
Opened 2023-07-31 08:18 UTC by Fujikawas

## Main changes of this PR
add default settings to IQN acceleration methods.

## Motivation and additional information
closes #1505 

## Author's checklist

* [x] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* [ ] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [x] I added a test to cover the proposed changes in our test suite.
* [ ] For breaking changes: I documented the changes in the appropriate [porting guide](https://precice.org/couple-your-code-porting-overview.html).
* [ ] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

2023-07-31 09:16 UTC, Fujikawas commented
The pre-conditioner type is set to "residual-sum" as default for all coupling schemes, not only for parallel-implicit coupling as mentioned in the issue.
I'm not sure about if we need to provide the default settings according to the coupling scheme types and if yes, how could we do it elegantly.

2023-08-03 11:46 UTC, uekerman requested changes
Very clean code, only a few additional tweaks needed.

2023-08-03 11:46 UTC, uekerman commented on docs/changelog/1754.md
> +- Add default settings about initial-relaxation, max-used-iterations, time-windows-reused, filter and preconsitioner to IQN-ILS and IQN-IMVJ acceleration methods
```suggestion
- Added default values for the IQN-ILS and IQN-IMVJ configuration options `initial-relaxation`, `max-used-iterations`, `time-windows-reused`, `filter`, and `preconditioner`.
```

2023-08-03 11:46 UTC, uekerman commented on tests/quasi-newton/serial/DefaultConfig.xml
> +      <!-- <time-windows-reused value="0" /> -->
```suggestion
```

2023-08-03 11:46 UTC, uekerman commented on src/acceleration/config/AccelerationConfiguration.hpp
> +    int         maxIterationsUsed          = 10;
```suggestion
    int         maxIterationsUsed          = 20;
```
Isn't 10 a bit too small?

2023-08-03 11:46 UTC, uekerman commented on src/acceleration/config/AccelerationConfiguration.cpp
> +        _preconditioner = PtrPreconditioner(new ResidualSumPreconditioner(_defaultValuesIQNILS.precond_nbNonConstTWindows));
Please don't comment lines out, but directly delete them. Will only confuse someone in three years. "Why is this commented out, should I comment it in again?"

2023-08-03 11:46 UTC, uekerman commented on src/acceleration/config/AccelerationConfiguration.cpp
> +  XMLAttribute<double> attrSingularityLimit(ATTR_SINGULARITYLIMIT, 1e-2);
I am not sure if we should change it here as well. 1e-2 is not a good default for QR1. 1e-16 is in a way as it means filter is off.

2023-08-03 11:46 UTC, uekerman commented on src/acceleration/config/AccelerationConfiguration.cpp
>      tagInitRelax.setDocumentation("Initial relaxation factor.");
I think we should add information on the default behavior in all of these documentation strings.

```suggestion
    tagInitRelax.setDocumentation("Initial relaxation factor. If tag is not provided, an initial relaxation of 0.1 is used.");
```

similarly below; also for filter and preconditioner

2023-08-03 11:47 UTC, uekerman commented
After merging this, let's consider updating some of our tutorials and also the documentation.

2023-08-23 15:07 UTC, merged