Fix returns in C bindings try blocks
precice/precice pull request #2076
Opened 2024-09-16 09:51 UTC by fsimonis

## Main changes of this PR

This PR fixes compiler errors due to missing return statements after `std::abort` in the C bindings, which is a workaround for compilers like gcc 10 that don't take the `noreturn` into account.

## Author's checklist

* [x] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* [ ] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [ ] I added a test to cover the proposed changes in our test suite.
* [ ] For breaking changes: I documented the changes in the appropriate [porting guide](https://precice.org/couple-your-code-porting-overview.html).
* [x] I sticked to C++17 features.
* [x] I sticked to CMake version 3.22.1.
* [ ] I squashed / am about to squash all commits that should be seen as one.

2024-09-16 10:33 UTC, fsimonis commented on extras/bindings/c/src/preciceC.cpp
> +const char *precicec_getVersionInformation() return precice::versionInformation;
Good catch! Missing brace.

What even are named return values? :eyes:

2024-09-16 10:59 UTC, davidscn requested changes
Fortran has the same problem

2024-09-16 15:15 UTC, fsimonis commented
Fortran needed some clean-up, but most were fine. The Fortran bindings use out arguments.

2024-09-17 07:02 UTC, davidscn approved these changes
Let's try this, I can check it once it is merged.

2024-09-17 08:14 UTC, merged