Indirect access
precice/precice pull request #2099
Opened 2024-10-11 12:40 UTC by davidscn

## Main changes of this PR

#1843 

## Motivation and additional information

## Author's checklist

* [ ] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* [ ] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [ ] I added a test to cover the proposed changes in our test suite.
* [ ] For breaking changes: I documented the changes in the appropriate [porting guide](https://precice.org/couple-your-code-porting-overview.html).
* [ ] I stuck to C++17 features.
* [ ] I stuck to CMake version 3.22.1.
* [ ] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

2024-11-26 09:04 UTC, uekerman commented on src/precice/Participant.cpp
> +}
```suggestion
void Participant::mapAndReadData(
    ::precice::string_view        meshName,
    ::precice::string_view        dataName,
    ::precice::span<const double> coordinates,
    double                        relativeReadTime,
    ::precice::span<double>       values) const
{
  _impl->mapAndReadData(toSV(meshName), toSV(dataName), coordinates, relativeReadTime, values);
}

void Participant::mapAndWriteData(
    ::precice::string_view        meshName,
    ::precice::string_view        dataName,
    ::precice::span<const double> coordinates,
    ::precice::span<const double> values)
{
  _impl->mapAndWriteData(toSV(meshName), toSV(dataName), coordinates, values);
}
```

2025-01-08 08:53 UTC, davidscn commented on src/mesh/config/MeshConfiguration.cpp
> +}
Why should we and what's wrong with the current approach? There is no value in having potentially multiple indirect access mappings.

2025-01-08 08:56 UTC, davidscn commented on src/mapping/MappingDataCache.hpp
> +struct MappingDataCache {
> This class is currently specific to PUM, right?

For the other methods, we still "need" to cache the time interpolation in the cache. Of course, we can still move it.

2025-01-08 09:34 UTC, davidscn commented on src/mapping/config/MappingConfiguration.cpp
> +                                                        "For indirect mesh access, one of both attributes has to be specified.");
```suggestion
    PRECICE_CHECK(!toMesh.empty() || !fromMesh.empty(), "Neither a \"to\" nor a \"from\" mesh was defined in a preCICE mapping. Most data mappings require a \"to\" and a \"from\" mesh. "
                                                        "For indirect mesh access, at least one of both attributes has to be specified.");

```

2025-01-08 15:42 UTC, davidscn commented on src/mapping/config/MappingConfiguration.cpp
> +    PRECICE_CHECK(!fromMesh.empty() || (fromMesh.empty() && dir == DIRECTION_WRITE && constraint == CONSTRAINT_CONSERVATIVE), "For indirect access, only read-consistent (direction = \"read\" and no \
Done

2025-01-10 13:29 UTC, davidscn commented on src/mapping/NearestNeighborBaseMapping.cpp
> +  }
We discussed this in person: the mesh is pre-filtered by the geometric filter, so it's fine to tag everything 👍

2025-01-13 13:16 UTC, davidscn commented on src/mapping/Mapping.hpp
> +  virtual void evaluateMappingDataCacheAt(::precice::span<const double> coordinates, const MappingDataCache &cache, ::precice::span<double> values);
Done

2025-01-13 13:17 UTC, davidscn commented on src/mapping/PartitionOfUnityMapping.hpp
> +  // Step 4: find all clusters the output vertex lies in, i.e., find all cluster centers which have the distance of a cluster radius from the given output vertex
Fixed

2025-01-13 13:17 UTC, davidscn commented on src/precice/config/ParticipantConfiguration.cpp
Done

2025-01-13 14:26 UTC, davidscn commented on src/precice/Participant.hpp
> +   * needs to be computed with every call of this function, whereas the other variant can efficiently precompute the mapping.
I adjusted the description now slightly. Please check again, I think that the statement is not negative in the first place and also a bit obvious from my perspective.

2025-01-13 14:43 UTC, davidscn commented on src/precice/Participant.hpp
> +   * The time associated to the data is derived from the last call of \ref advance().
What's wrong with this sentence? Do you think it is confusing? It might be valuable to get forward this information to the user, that the data is attached to a time stamp, and this is the way we handle this internally in preCICE/the API.

2025-01-13 15:12 UTC, davidscn commented on src/precice/Participant.hpp
> +  /**
Gave it its own section with some docs.

2025-01-16 11:59 UTC, davidscn commented on tests/parallel/direct-mesh-access/AccessReceivedMeshAndMapping.cpp
> +// participant is zero ( last entry in l115 {15, 16, 0}).
FYI @uekerman it might happen that vertices are now essentially not visible to the users or filtered out, but I guess that's a logical consequence of how we do now things.

2025-01-29 07:14 UTC, uekerman commented on src/precice/Participant.hpp
> +   * @note Note that the evaluated mapping computes the values corresponding to the initial configuration of the other provided mesh.
I could imagine that this formulation is confusing. For preCICE, there is only one configuration, we could call it "initial configuration", but it could also be sth different. For a mesh-particle coupling, the mesh and the particle solver need agree on what to couple. If the mesh solver uses an ALE approach and the particle solver wants to reuse the deformation, you probably have to communicate velocities and mesh deformation. But those are two separate fields and then the particle solver (or the adapter) needs to take to care to use these two the correct way.

Instead of having this sentence here (I would simply remove it), it would be better to eventually have a "6-way" coupled tutorial, we could point to from the docs.

2025-02-18 14:02 UTC, uekerman requested changes
Code looks very clean, but is too enormous to properly review. I could not look at all details of the implementation, but have to trust the tests. Instead, I mainly focused on user-facing things. Tests look very good.

Remarks:
- Shouldn't it be possible to also add unit tests for the new mapping functions?
- We have a dependency on https://github.com/precice/preeco-orga/issues/31 if we want to make calling `setMeshAccessRegion` mandatory.
- Is there an integration test combining JIT with direct access?
- When reading at different points in time and at different locations, is there a performance-wise better order? "First all locations at time one, then all location at time two" or "First time one and two at location one, then time one and two at location two, ..."? If yes, we should properly document as an example in the user docs.

2025-02-20 20:01 UTC, davidscn commented on src/precice/Participant.hpp
> +   * The time associated to the data is derived from the last call of \ref advance().
Ok, then I remove it.

2025-02-20 20:24 UTC, davidscn commented on tests/parallel/just-in-time-mapping/ExplicitRead.cpp
> +          PRECICE_ASSERT(false);
Yes, but we want to test the correctness of preCICE and not the correctness of the test, right? Semantically, this should be an ASSERT from my understanding. A failing test would indicate malicious behavior in preCICE.

2025-02-20 20:24 UTC, davidscn commented on tests/parallel/just-in-time-mapping/ExplicitRead.cpp
> +        PRECICE_ASSERT(false);
See above

2025-02-21 15:01 UTC, davidscn commented on tests/parallel/direct-mesh-access/AccessReceivedMeshAndMapping.cpp
> +// participant is zero ( last entry in l115 {15, 16, 0}).
The user gets a warning if vertices are filtered out completely during the repartitioning. That's here, however, not the case. We also can't give a warning, as anyway vertices are outside the box due to the halo-region required for the just-in-time mapping.

2025-02-21 15:18 UTC, davidscn commented on src/precice/Participant.hpp
> +   * runs, using coordinates outside the defined bounding box will throw an error.
The comment was related to the necessity of defining a box. I removed the confusing part.

2025-02-21 15:20 UTC, davidscn commented on src/precice/Participant.hpp
> +   * @note this function is currently part of the experimental API.
Fixed

2025-02-21 15:24 UTC, davidscn commented on src/precice/Participant.hpp
> +   * @note this function is currently part of the experimental API.
Put it now below the `@brief`

2025-02-21 15:26 UTC, davidscn commented on src/precice/impl/ParticipantImpl.cpp
> +  // TODO: We need to reset here the buffer for just-in-time mappings as well
No, was a leftover

2025-02-21 15:26 UTC, davidscn commented on src/precice/impl/ParticipantImpl.cpp
> +  // TODO: Make these checks conditional
was outdated

2025-02-21 16:23 UTC, davidscn commented on src/precice/Participant.hpp
> +   * @note Note that the evaluated mapping computes the values corresponding to the initial configuration of the other provided mesh.
I removed it now, though I believe awareness would be good here.

2025-02-21 16:56 UTC, davidscn commented on src/mapping/MappingDataCache.hpp
> +struct MappingDataCache {
Moved it to `impl` and added more docs. Reopen if necessary.

2025-02-21 17:07 UTC, davidscn commented on src/mapping/Mapping.hpp
> +   * first sample in time and then compute an interpolant in time and then interpolate in space.
Yes, this was confusing, rephrased it a bit.

2025-02-21 17:11 UTC, davidscn commented on src/mapping/Mapping.hpp
> +  virtual void updateMappingDataCache(MappingDataCache &cache, Eigen::VectorXd &in);
added

2025-02-21 17:13 UTC, davidscn commented on src/precice/impl/ParticipantImpl.cpp
> +    // context.finishJustInTimeWriteMapping();
No, already handled a few lines below.

2025-02-21 20:24 UTC, davidscn commented on src/mapping/Mapping.hpp
> +  virtual void completeJustInTimeMapping(MappingDataCache &cache, Eigen::Ref<Eigen::MatrixXd> buffer);
Added (also in the datacontext)

2025-02-21 20:24 UTC, davidscn commented on src/precice/impl/DataContext.hpp
> +   * @brief
added

2025-02-21 20:24 UTC, davidscn commented on src/precice/impl/WriteDataContext.hpp
> +  void completeJustInTimeMapping();
done

2025-02-26 07:18 UTC, davidscn commented
>     * Shouldn't it be possible to also add unit tests for the new mapping functions?

Added unit tests for the PUM part.

>     * Is there an integration test combining JIT with direct access?
> 

Also added those and checked for the initialization (jit + direct) in various additional places.

>     * When reading at different points in time and at different locations, is there a performance-wise better order? "First all locations at time one, then all location at time two" or "First time one and two at location one, then time one and two at location two, ..."? If yes, we should properly document as an example in the user docs.

Yes. I added a note in the API docs already and will add a more elaborate example in the website docs.

2025-03-03 13:11 UTC, uekerman commented on tests/parallel/direct-mesh-access/AccessReceivedMeshAndMapping.cpp
> +// participant is zero ( last entry in l115 {15, 16, 0}).
OK, then we did what we could.

2025-03-03 13:14 UTC, uekerman commented on tests/parallel/just-in-time-mapping/ExplicitRead.cpp
> +          PRECICE_ASSERT(false);
But the `time` variable you get indirectly from preCICE, so it would be triggered by malicious behavior in preCICE, no? Probably an edge case. Two disadvantages: `PRECICE_ASSERT` does not get triggered in release builds and leads to a crash in the tests.

2025-03-03 13:22 UTC, uekerman approved these changes

2025-03-03 13:22 UTC, uekerman commented on docs/changelog/2099.md
> +- Renamed the 'direct-access' flag in `<receive-mesh direct-access="..." />` to 'api-access' `<receive-mesh api-access="..." />`.
```suggestion
- Renamed the 'direct-access' flag in `<receive-mesh direct-access="..." />` to 'api-access' `<receive-mesh api-access="..." />` and deprecated `direct-access`.
```

2025-03-03 13:22 UTC, uekerman commented on docs/changelog/2099.md
> +- The API functions "setMeshAccessRegion" and "getMeshVertexIDsAndCoordinates" require now the flag api-access="true". If not set, the function will throw an error.
```suggestion
- Fixed the API functions "setMeshAccessRegion" and "getMeshVertexIDsAndCoordinates" to now require the flag api-access="true". If not set, the function will throw an error.
```
To make it clearer that we do not consider this breaking.

2025-03-03 13:22 UTC, uekerman commented on docs/changelog/2099.md
> +- When combining direct-mesh access with mappings, the function "getMeshVertexIDsAndCoordinates" will return only the vertices within the defined access region ("setMeshAccessRegion"). Setting an acc
```suggestion
- Changed the behavior of the function "getMeshVertexIDsAndCoordinates", when combining direct-mesh access with mappings, to return only the vertices within the defined access region ("setMeshAccessRegion"). Setting an access region is mandatory if no other mapping is defined. In parallel, it has been mandatory anyway.
```

2025-03-03 13:22 UTC, uekerman commented on docs/changelog/2099.md
> +- Added experimental support for an just-in-time mapping with NN and PU-RBF mapping via the new API functions 'mapAndReadData' and 'mapAndWriteData'.
```suggestion
- Added experimental support for just-in-time mapping with NN and PU-RBF via the new API functions 'mapAndReadData' and 'writeAndMapData'.
```

2025-03-03 15:19 UTC, BenjaminRodenberg requested changes
I did a quick incomplete review. Two important things:

* `Participant.cpp` and `ParticipantConfiguration.cpp` are already huge and this PR adds a lot of code for both classes. I think there is a lot of potential for refactoring to move code from these two (huge) classes into other classes that are not as complicated.
* Many tests already cover the case `substeps="true"`. However, since we are planning to set `substeps="true"` as the new default it would be important to also test the integration of this feature with the new default and see if any tests break. I'm currently preparing a PR here https://github.com/precice/precice/pull/2220.

2025-03-03 15:19 UTC, BenjaminRodenberg commented on src/precice/impl/ParticipantImpl.cpp
> +      }
Could be factored into `_accessor`. Then call `_accessor.initializeMappingDataCache(mappingType)` here.

2025-03-03 15:19 UTC, BenjaminRodenberg commented on src/precice/impl/ParticipantImpl.cpp
>      context.resetBuffer();
```suggestion
    // reset the buffered data here
    context.resetBufferedData()
```

and create function inside `WriteDataContext`:

```
void resetBufferedData() {
    invalidateMappingCache(true);
    resetBuffer();  // <- make private or even inline?
}
```

2025-03-03 15:19 UTC, BenjaminRodenberg commented on src/precice/impl/MeshContext.hpp
> +  /// MappingContext
Odd line breaking

2025-03-03 15:19 UTC, BenjaminRodenberg commented on src/precice/impl/DataContext.hpp
> +      mappingCache->setTimeStamp(-1);
? The `-1` looks to me like a hack. Why don't define a new function with a better name in the `MappingDataCache`?

```
void MappingDataCache::functionWithDescriptiveName() {
    setTimeStamp(-1);  // add a comment here what -1 means
}
```

2025-03-03 15:19 UTC, BenjaminRodenberg commented on src/precice/config/ParticipantConfiguration.cpp
> +    }
Both `if`-legs could be moved into `MeshContext`. Maybe even the whole block could be moved inside `Mesh`.

2025-03-03 15:26 UTC, davidscn commented
> However, since we are planning to set substeps="true" as the new default it would be important to also test the integration of this feature with the new default 

I don't understand exactly how this is related to the changes here. As already mentioned, we test here both, substeps="true" and substeps="false". When we change the default in other places, then we either have to explicitly set substeps="false" in failing tests or change the test to test what is supposed to be the correct result. What are you expecting now in this PR?

2025-03-03 17:30 UTC, BenjaminRodenberg commented
> What are you expecting now in this PR?

Would be interesting to test how the new default and this PR integrates to avoid that suddenly all tests break one day before the release. But I also see this as optional and something that we can check very quickly when either this PR or #2220 is ready to merge. Like you also said: There are plenty of tests that take care about `substeps="true"`.

Much more important is from my perspective the refactoring.

2025-03-04 09:26 UTC, fsimonis commented on src/mapping/RadialBasisFctSolver.hpp
> +    out -= static_cast<Eigen::MatrixXd>(_qrMatrixQ.transpose().solve(-epsilon));
Why the static cast?

2025-03-04 09:26 UTC, fsimonis commented on src/mapping/config/MappingConfiguration.cpp
> +    PRECICE_CHECK(fromMesh.get() != nullptr,
This should be equivalent

```suggestion
  if (!fromMesh && fromMeshName.empty()) {
    PRECICE_CHECK(toMesh,
                  "Mesh \"{0}\" was not found while creating a mapping. "
                  "Please correct the to=\"{0}\" attribute.",
                  toMeshName);
    fromMesh = mesh::MeshConfiguration::getJustInTimeMappingMesh(toMesh->getDimensions());
  }
  if (!toMesh && toMeshName.empty()) {
    PRECICE_CHECK(fromMesh,
```

2025-03-04 09:31 UTC, davidscn commented on extras/bindings/fortran/src/preciceFortran.cpp
> +    const int * size,
I had the same question when doing this. In its current shape, the design should be coherent with other fortran API functions.

2025-03-04 13:15 UTC, davidscn commented on src/precice/impl/MeshContext.hpp
> +  /// MappingContext
these are individual paragraphs. I can put another empty line in between if this makes it less odd?

2025-03-04 13:34 UTC, davidscn commented on src/precice/impl/ParticipantImpl.cpp
>      context.resetBuffer();
put it inline

2025-03-04 13:44 UTC, BenjaminRodenberg commented on src/precice/impl/MeshContext.hpp
> +  /// MappingContext
Why not a multiline comment? You could also add bullet points in the multiline comment to have a better formatting? Right now I really do not understand the rationale behind the line breaks.

2025-03-04 13:56 UTC, davidscn commented on src/precice/impl/MeshContext.hpp
> +  /// MappingContext
I removed the line break

2025-03-04 14:00 UTC, davidscn commented on src/precice/config/ParticipantConfiguration.cpp
> +    }
I am not sure. Then using two functions or what do you have in mind? The two branches are different: input vs output, but also the context we append our own vector to.

2025-03-04 14:02 UTC, davidscn commented on docs/changelog/2099.md
> +- Fixed the API functions "setMeshAccessRegion" and "getMeshVertexIDsAndCoordinates" to now require the flag api-access="true". If not set, the function will throw an error.
Extended the second point

2025-03-04 14:04 UTC, davidscn commented on src/mapping/RadialBasisFctSolver.hpp
> +    out -= static_cast<Eigen::MatrixXd>(_qrMatrixQ.transpose().solve(-epsilon));
the result of `solve()` (or in general intermediate results in Eigen) is an Eigen internal type. Sometimes, these things are simply views to delay and merge operations defined on those. In this case, the `-=` operator is not defined on the return type of `solve()`. Hence, we explicitly need to cast (i.e., materialize) the result before using the operator.

2025-03-04 14:07 UTC, davidscn commented on src/mapping/config/MappingConfiguration.cpp
> +    PRECICE_CHECK(fromMesh.get() != nullptr,
Applied it locally to also address the other spots

2025-03-04 14:09 UTC, fsimonis commented on src/precice/impl/ParticipantImpl.cpp
> +                                [bb = context.userDefinedAccessRegion](const auto &v) { return bb->contains(v); });
Let's start moving these to `mesh/Utils.hpp`.

```suggestion
    auto result = mesh::countInBB(context.mesh, context.userDefinedAccessRegion);
```

2025-03-04 14:29 UTC, davidscn commented on src/precice/impl/DataContext.hpp
> +      justInTimeMapping->initializeMappingDataCache(*mappingCache.get());
Didn't remember this somehow

2025-03-04 14:30 UTC, davidscn commented on src/precice/impl/MeshContext.hpp
> +  std::shared_ptr<mesh::BoundingBox> userDefinedAccessRegion;
Yes, a `unqiue_ptr` deletes the copy constructor, which we need due to shared ownership the the meshcontext itself.

2025-03-04 14:44 UTC, BenjaminRodenberg commented on src/precice/config/ParticipantConfiguration.cpp
> +    }
I mean something in this direction:

```
    if (!input->isJustInTime()) {
      participant->doInputConfiguration(fromMesh, map, mappingContext);
    }
    if (!output->isJustInTime()) {
      participant->doOutputConfiguration(toMesh, map, mappingContext);
    }
```

Maybe some input arguments are not needed. This has two main debefits:

1. the code becomes more readable: you replace the low-level implementation with a high-level function with a descriptive name. 
2. it improves encapsulation: you do not need to access `participant->meshContext(...)` anymore from here but only inside `participant`.

2025-03-04 14:51 UTC, davidscn commented on src/precice/impl/ParticipantImpl.cpp
> +    PRECICE_DEBUG("Filtered {} of {} vertices out on mesh {} due to the local access region. Mesh size in the access region: {}", context.mesh->nVertices() - result, context.mesh->nVertices(), meshNa
moved to mesh utils

2025-03-04 14:53 UTC, davidscn commented on extras/bindings/fortran/src/preciceFortran.cpp
> +    const int * size,
Discussion in person: using a pointer is correct

2025-03-04 15:10 UTC, davidscn commented on src/precice/config/ParticipantConfiguration.cpp
> +    }
Done

2025-03-04 15:11 UTC, davidscn commented on tests/parallel/just-in-time-mapping/ExplicitRead.cpp
> +          PRECICE_ASSERT(false);
done

2025-03-04 15:20 UTC, davidscn commented on src/mapping/impl/MappingDataCache.hpp
> +struct MappingDataCache {
contradicts a bit the comment from @BenjaminRodenberg, who mentioned that having descriptive function names for setting times etc improved code readability. I don't have a strong opinion here

2025-03-04 15:21 UTC, davidscn commented on src/mesh/config/MeshConfiguration.cpp
> +  static std::map<int, mesh::PtrMesh> meshes;
Discussion in person: I removed the static declaration: we will have now one mesh per jit mapping

2025-03-04 15:22 UTC, davidscn commented on src/mesh/config/MeshConfiguration.cpp
> +  return meshes[dimension];
Obsolete after https://github.com/precice/precice/pull/2099#discussion_r1979676714

2025-03-04 15:45 UTC, davidscn commented on src/precice/impl/MeshContext.hpp
> +  std::shared_ptr<mesh::BoundingBox> userDefinedAccessRegion;
using a std::optional would also (hard-) copy the bounding box. I think it would be more safe to keep it as a shared owner ship, even though it is shared among various mesh contexts.

2025-03-04 15:51 UTC, davidscn commented on src/precice/impl/ParticipantImpl.cpp
> +    context.invalidateMappingCache(false);
Done

2025-03-04 16:11 UTC, davidscn commented on src/mapping/NearestNeighborMapping.cpp
> +  Eigen::Map<const Eigen::MatrixXd> inMap(inData.values.data(), valueDimensions, input()->nVertices());
Same as here 

https://github.com/precice/precice/pull/2099#discussion_r1979661095

2025-03-04 16:30 UTC, davidscn commented on src/mapping/impl/MappingDataCache.hpp
> +  // however, there doesn't seem to be any compatible interface in time::Sample, so we simply use a vector here
Moved now to `Stamples` and all private members are gone. We then need the getters and setters to access the `inData` stamples, otherwise this is not entirely clear in my opinion

2025-03-04 16:31 UTC, davidscn commented on src/mapping/impl/MappingDataCache.hpp
> +struct MappingDataCache {
Moved now to Stamples and all private members are gone. We then need the getters and setters to access the inData stamples, otherwise this is not entirely clear in my opinion

2025-03-04 17:29 UTC, merged