Add relative times to profiling analyse
precice/precice pull request #2154
Opened 2024-12-13 15:14 UTC by fsimonis

## Main changes of this PR

This PR adds relative times to the output of `precice-profiling analyze` and limits the output format to 2 decimal places.

## Motivation and additional information

Closes #1988 
Closes #2048

## Author's checklist

* [x] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* [ ] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [ ] I added a test to cover the proposed changes in our test suite.
* [ ] For breaking changes: I documented the changes in the appropriate [porting guide](https://precice.org/couple-your-code-porting-overview.html).
* [x] I stuck to C++17 features.
* [x] I stuck to CMake version 3.22.1.
* [ ] I squashed / am about to squash all commits that should be seen as one.

2024-12-16 12:14 UTC, davidscn requested changes
While trying to run this example, I got

```bash
Selection contains the primary rank 0 and secondary rank None.
~/precice/tools/profiling//precice-profiling:639: UserWarning: Comparisons with None always result in null. Consider using `.is_null()` or `.is_not_null()`.
  ldf.filter(pl.col("rank") == rank)
Traceback (most recent call last):
  File "~/precice/tools/profiling//precice-profiling", line 1011, in <module>
    sys.exit(dispatcher.get(args.cmd, showHelp)(args))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/precice/tools/profiling//precice-profiling", line 992, in <lambda>
    "analyze": lambda ns: analyzeCommand(
                          ^^^^^^^^^^^^^^^
  File "~/precice/tools/profiling//precice-profiling", line 658, in analyzeCommand
    printWide(joined)
  File "~/precice/tools/profiling//precice-profiling", line 109, in printWide
    width = max(width, headerWidth)
```

using the command `precice-profiling analyze --event "partition.broadcastMesh.A-Mesh" B`.

Also this will once again nuke my stats gathering in ASTE as the columns change, I will have to try.

2025-01-22 15:37 UTC, fsimonis commented
@davidscn Fixed the bug. Turned out that selecting a primary-only event wasn't supported all along.

2025-03-19 11:51 UTC, fsimonis commented
Rebased, CI ran, and tested locally.

2025-03-19 12:04 UTC, davidscn commented
The output
```
~: precice-profiling -u s analyze Fluid
Reading events file profiling.json
Output timing are in s.
Selection contains the primary rank 0, the cheapest secondary rank 2, and the most expensive secondary rank 1.
 name                                       │ R0:sum R0:%   R0:count R0:mean R0:min R0:max │ R2:sum R2:%   R2:count R2:mean R2:min R2:max │ R1:sum R1:%   R1:count R1:mean R1:min R1:max
 ───────────────────────────────────────────┼─────── ────── ──────── ─────── ────── ───────┼─────── ────── ──────── ─────── ────── ───────┼─────── ────── ──────── ─────── ────── ──────
 total                                      │   1.48 100.00        1    1.48   1.48   1.48 │   1.48 100.00        1    1.48   1.48   1.48 │   1.48 100.00        1    1.48   1.48   1.48
   advance                                  │   0.01   0.81        3    0.00   0.00   0.00 │   0.01   0.67        3    0.00   0.00   0.00 │   0.01   0.68        3    0.00   0.00   0.00
     advanceCoupling                        │   0.01   0.61        3    0.00   0.00   0.00 │   0.01   0.56        3    0.00   0.00   0.00 │   0.01   0.55        3    0.00   0.00   0.00
       receiveConvergence                   │   0.01   0.45        3    0.00   0.00   0.00 │   0.01   0.52        3    0.00   0.00   0.00 │   0.01   0.40        3    0.00   0.00   0.00
       waitAndReceiveData                   │   0.00   0.06        3    0.00   0.00   0.00 │   0.00   0.00        3    0.00   0.00   0.00 │   0.00   0.03        3    0.00   0.00   0.00
       waitAndSendData                      │   0.00   0.04        3    0.00   0.00   0.00 │   0.00   0.00        3    0.00   0.00   0.00 │   0.00   0.08        3    0.00   0.00   0.00
     mapping                                │   0.00   0.10        6    0.00   0.00   0.00 │   0.00   0.04        6    0.00   0.00   0.00 │   0.00   0.07        6    0.00   0.00   0.00
     syncTimestep                           │   0.00   0.02        3    0.00   0.00   0.00 │   0.00   0.00        3    0.00   0.00   0.00 │   0.00   0.00        3    0.00   0.00   0.00
   construction                             │   0.27  18.37        1    0.27   0.27   0.27 │   0.27  18.37        1    0.27   0.27   0.27 │   0.27  18.37        1    0.27   0.27   0.27
     com.initializeIntraCom                 │   0.00   0.01        1    0.00   0.00   0.00 │   0.09   6.33        1    0.09   0.09   0.09 │   0.10   6.61        1    0.10   0.10   0.10
     com.initializeMPI                      │   0.00   0.00        1    0.00   0.00   0.00 │   0.00   0.00        1    0.00   0.00   0.00 │   0.00   0.00        1    0.00   0.00   0.00
     configure                              │   0.27  18.32        1    0.27   0.27   0.27 │   0.18  12.01        1    0.18   0.18   0.18 │   0.17  11.73        1    0.17   0.17   0.17
   finalize                                 │   0.00   0.08        1    0.00   0.00   0.00 │   0.00   0.15        1    0.00   0.00   0.00 │   0.00   0.16        1    0.00   0.00   0.00
   initialize                               │   1.11  74.76        1    1.11   1.11   1.11 │   1.11  74.78        1    1.11   1.11   1.11 │   1.11  74.77        1    1.11   1.11   1.11
     initalizeCouplingScheme                │   0.00   0.03        1    0.00   0.00   0.00 │   0.00   0.01        1    0.00   0.00   0.00 │   0.00   0.01        1    0.00   0.00   0.00
     m2n.requestPrimaryRankConnection.Solid │   1.01  68.11        1    1.01   1.01   1.01 │   1.01  68.14        1    1.01   1.01   1.01 │   1.01  68.13        1    1.01   1.01   1.01
     mapping                                │   0.00   0.26        2    0.00   0.00   0.00 │   0.01   0.53        2    0.00   0.00   0.01 │   0.00   0.23        2    0.00   0.00   0.00
   solver.advance                           │   0.09   5.94        4    0.02   0.00   0.03 │   0.09   5.99        4    0.02   0.00   0.03 │   0.09   5.98        4    0.02   0.00   0.03
     readData.Fluid-Mesh_Displacement       │   0.00   0.01        4    0.00   0.00   0.00 │                                              │   0.00   0.01        4    0.00   0.00   0.00
     writeData.Fluid-Mesh_Force             │   0.00   0.00        3    0.00   0.00   0.00 │                                              │   0.00   0.00        3    0.00   0.00   0.00
   solver.initialize                        │   0.00   0.02        1    0.00   0.00   0.00 │   0.00   0.02        1    0.00   0.00   0.00 │   0.00   0.02        1    0.00   0.00   0.00
     setMeshVertices.Fluid-Mesh             │   0.00   0.01        1    0.00   0.00   0.00 │   0.00   0.00        1    0.00   0.00   0.00 │   0.00   0.00        1    0.00   0.00   0.00

2025-03-19 12:05 UTC, davidscn approved these changes
Looks very nice!

2025-03-19 12:05 UTC, merged